### ISSUE TITLE
Have you  forgotten about pushing the code?

### ISSUE THREAD

**Issue by Eternal-Br** [mosamdabhi/neural-shape-prior#1]
6 months passed, have you  forgotten about pushing the code? guys?
Does it mean "OPEN SOURCE" that just building a blank github repo?

**Comment by mosamdabhi** [comment]
Apologies for the delay.

"**neural-shape-prior**" module is also implemented in the [MBW: Multiview Bootstrapping in the Wild](https://github.com/mosamdabhi/MBW/tree/main/modules/mvnrsfm) codebase, as "**MV-NRSfM**" module. 

We plan to release a standalone "**neural-shape-prior / MV-NRSfM**" on this GitHub repository in the next few days.
